### ISSUE TITLE
프로젝트 환경설정

### ISSUE THREAD

**Issue by hemudi** [Doing-Mate/doing-mate-fe#1]
## Todo
- [x] Vite 를 이용하여 React 프로젝트 환경설정
- [x] Styled components 패키지 설치
- [x] GlobalStyle을 이용한 reset CSS 적용

## Memo
1월 6일 토요일 1시에 페어 프로그래밍으로 진행
