### ISSUE TITLE
라벨 컴포넌트 구현

### ISSUE THREAD

**Issue by HYUNJI0624** [Doing-Mate/doing-mate-fe#5]
### Todo

- [x] Title Label 구현
- [x] Month Label 구현
- [x] Category Label 구현
- [x] 비서봇 Message Label 구현
- [x] Story Book 활용하여 테스트 코드 작성
